# ---------------------------------------------------------------------------
# Top-level Terragrunt config — shared across external provider stacks.
# ---------------------------------------------------------------------------
# Included by each external stack's terragrunt.hcl via:
#   include "root" { path = find_in_parent_folders("root.hcl") }
#
# Kubernetes stacks have their own kubernetes/root.hcl (found first by
# find_in_parent_folders) and never see this file.
#
# Backend-agnostic: every stack declares its own backend "s3" in its .tf files.
# Credentials come from TF_VAR_* env vars exported by .envrc.

terraform_binary = get_env("TERRAGRUNT_TFPATH", "tofu")

locals {
  # ---------------------------------------------------------------------------
  # MinIO S3 backend endpoint override (Cloudflare Access workaround)
  # ---------------------------------------------------------------------------
  # https://minio.noizu.com sits behind Cloudflare Access, so `tofu init` gets a
  # 302 HTML login page instead of an S3 ListObjectsV2 response. AWS_ENDPOINT_URL_S3
  # does NOT help — an explicit `endpoints` in the backend block always wins.
  #
  # Stacks whose backend block is generated by Terragrunt (cloudflare/zones/*)
  # read TG_MINIO_ENDPOINT directly. Stacks with a checked-in backend.tf /
  # provider.tf can only be overridden at init time via -backend-config, so
  # scripts/tg-minio.sh also writes an HCL override file and points
  # TG_MINIO_BACKEND_CONFIG at it.
  #
  # Unset (the default) => empty argument list => behavior is byte-identical to
  # before for anyone not using the port-forward flow.
  minio_backend_config = get_env("TG_MINIO_BACKEND_CONFIG", "")
}

terraform {
  extra_arguments "minio_backend_override" {
    commands  = ["init"]
    arguments = local.minio_backend_config == "" ? [] : ["-backend-config=${local.minio_backend_config}"]
  }
}
