domain: therobotdrafts.com
appDomain: app.therobotdrafts.com

backend:
  image: ops.noizu.com/therobotdrafts/backend:latest
frontend:
  image: ops.noizu.com/therobotdrafts/frontend:latest

database:
  name: therobotdrafts_dev

sso:
  domains: "therobotdrafts.com=oidc"
  autoApproveDomains: ""
