---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: clickhouse-secrets
  namespace: infra
spec:
  encryptedData:
    SIGNOZ_TOKENIZER_JWT_SECRET: AgCiUlpu26xY53cAfrBf7jrtYFcvYWRHo1okF/qGPypY5oN20yrr15UKGIvG2U9yqt94fT/CJwvx7YGX0YK6dyfQ4IevGejbE7wekgIcVefUCNkedYEoEiaZ/u/0TDYl4Wy2IWvlagT2cmFNeeFidQx8THELgurkUga/e+9k3gBaYYekn+rJUD+8hrqRKPxax1NMOFtw44GKTdylaklqzr6O61wracoBsonAvx59OZk4wjM65DBBUjMGcKebO5J5n4//HijCqkqEdKOGkOuElBakKGzqZyzI6ao/Ek2ZCTKl1LXQHnKiSbrIh3Q9eCXj8dQphIHylDWQ7AuPFVKd+lO9YbVWNLZJyWMqQX5HOzJESw1M/YG6QUAlKuTcAz6B7lr4/4lK9lMPRrJ+kp9QDCif6YIapv6t+t0iaiGiBsXTRXuxbiaxDsN2hsHz3sCNfqGcRAr6dvoeBnYlOUi9qybeeyeXXJdKdhi3jhRZR04eGAnri+Thr99pE0GFrKu6BMTgPFhZYS/Wj42wGMbHtbIayEfQOi8ntV+ox0hMejaPlRw3Or5PIou8r9YI6heuESGqvNq8cr1jT+8i38gn5MWQcg1cdEkXK8b/ZsVobAIwR2tdUIt6ucK0NRle+ii0HFyuLJNGrfabmuB/NyEbpLGs3Mca4T3ZzIv4e/uBdCj7IGisfO+ArNWBIBJOlEMDFCz/hHYxZoUxoANB4j1wIi5gEBvtB6h/yCsClJOZrZA0BstRTwESjFTDewPug6+LoTnznDrtoHvrCgH6p+rRHSQ2
  template:
    metadata:
      name: clickhouse-secrets
      namespace: infra
