---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-basic-auth
  namespace: infra
spec:
  encryptedData:
    auth: AgBFEQPM61/L3IhYLy5uS8iAJ6GNOtHyPNOn1AMavDjnjyCGf9ee2ZadEog7sEqnWWoKE0E0d0fQ70QzM3+LiXMMIxuUFA2ORlP9E6S41nv4+Be14wTLG43ylnakGsB4sp9vvE581DUgpVhcbLY3xdmSZYcoR8mivaLlA0KpwYnXZRnHDd9UQsXEb/wUbM6/BQUp3kSueu7re7tbDjzs5JUi0kqWzslOkMYm3aOB42Q3Xb5h6nhktQopJQEWX93tqnzlfcldI9avppOSkLi03zlLawRLKR3bUYhtOLecH41IVrsEEuiqzefZ1n+I5Q/O/Fc7V+pQ4UEILUPr+ZbPrDZ3Z+tf6ufVTkV2b1qqIQTQVV4YviTCZlDIJNiZN/78Ixl9RaDSWXO41uZM5DCcX+GRQF+UH1sArisjPKQIAqTHtveBUZOygKgoZFOnPg/AjyhKK4MOnJ0Fn8YrdY/uTk/OGfUSvceVpDGEekRa6LAg8e5wz9VDdpKc3zNfzqeXwQpARpE8YRRuSEMPfGoih6FSLRB5ufvzyxCnYlbX/1DHYqw1R2okhfBhUODFFevkrUJzptQVfInzJ0eus2FKcU4qrvRDxZHkmdKbEXGZvO4WW2G32cCC4UNexcuekCLmDPg6x+HMRVDkM/Mus7OJv+7ZUc1EoqwgXbl0fiwxlQ7UMGjJbn/BB2uA+OEIjTLB/S9qJkPkHCtZiYSrdHa5EkESmsRa+L/H2dGOITHWc+ucHpQ6KgbNKNEr6RWkiBjWSsreU6fLF46/kTRildyN9qwb
  template:
    metadata:
      name: registry-basic-auth
      namespace: infra
