import type { StyleGuideConfig } from "../types";

/** Properties that get a --layout-{name}-{prop} var indirection */
const VAR_PROPS = new Set(["max-width", "padding", "margin", "content-bg"]);

// ⟦𓄇𓍜𓊞𓉮⟧ generateLayoutCSS :: auto-generated pointer for public function generateLayoutCSS
export function generateLayoutCSS(_config: StyleGuideConfig): string {
  // Layout CSS is now generated by scoped-vars
  return "";
}
