server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location = /healthz {
    access_log off;
    add_header Content-Type text/plain;
    return 200 "ok\n";
  }

  location = /auth/oidc {
    return 302 https://auth.derobot.is/application/launch/therobotlearns/;
  }

  location = /login {
    try_files /index.html =404;
  }

  location = /signup {
    try_files /index.html =404;
  }

  location /quiz/ {
    try_files $uri $uri/ /quiz/index.html;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
