replicas: 1
domain: accords.derobot.is

image: ops.noizu.com/derobot.is/accords:v1.0.0
port: 8080

resources:
  requests:
    cpu: 25m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 64Mi

imagePullSecrets:
  - name: ops-registry-secret

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
  cloudflareOnly: true

tls:
  enabled: true
  secretName: accords-tls
  infisical:
    enabled: true
    resyncInterval: 300
    hostAPI: "https://infisical.noizu.com/api"
    credentialsSecret: universal-auth-credentials
    credentialsNamespace: infra
    projectSlug: k8-infra
    envSlug: prod
    secretsPath: "/apps/tls/derobotis"
    crtKey: DEROBOTIS_TLS_CRT
    keyKey: DEROBOTIS_TLS_KEY
    caKey: ""
