defmodule Styleguide do
  @moduledoc """
  Hologram-based style guide viewer for the Noizu design system.

  Theme CSS is generated by the Node styleguide engine (`../app`) and served
  from `priv/static/themes/`. UI primitives and showcases are Hologram components.
  """
end
