schema: "noizu.start_app.base_hydration.v1"
start_app:
  version: "0.1.0"
  source:
    template_path: "/Users/keithbrings/Work/Space/Infra/Noizu/components/start-app"
    tarball_path: "/Users/keithbrings/Work/Space/Infra/Noizu/components/start-app/start-app.tar.gz"
    tarball_md5: "6e014fa3d650a54a0b71e0fa91b101ff"
hydration:
  tool: "init-proj-scaffold"
  hydrated_at: "2026-07-22T13:28:28Z"
  args:
    project_dir: "therobotlearns.com"
    slug: "trl"
    elixir_module: "TheRobotLearns"
    target: "/Users/keithbrings/Work/Space/Infra/Noizu/projects/therobotlearns.com/app"
    helm_mode: "force"
  derived:
    web_module: "TheRobotLearnsWeb"
    otp_app: "the_robot_learns"
    otp_app_web: "the_robot_learns_web"
    db_name: "therobotlearns_com_dev"
    db_name_test: "therobotlearns_com_test"
    frontend_name: "trl-frontend"
    host_port: "8080"
start_app_scaffold:
  applied: false
