locals {
  account_id = "a75e745949fc104ea4c4107a17158f15"
  zone_id    = "46014d24206a7141ed698d2d9d963e85"
  ip         = "208.64.36.79"
  mail_ip    = "208.64.36.80"
  ipmi_ip    = "208.64.36.78"

  cluster_subdomains = toset([
    "accounting",
    "apm",
    "appsmith",
    "argocd",
    "blog",
    "bottlecrm",
    "chartdb",
    "chatterbox-tts",
    "cockpit",
    "code",
    "directus",
    "docmost",
    "drawio",
    "echelon",
    "espocrm",
    "eval",
    "excalidraw",
    "ghost",
    "growthbook",
    "hakatime",
    "headlamp",
    "inference",
    "infisical",
    "infra",
    "jupyter",
    "keygen",
    "kimai",
    "kitten-tts",
    "kroki",
    "labelstudio",
    "langfuse",
    "listmonk",
    "litellm",
    "livecodes",
    "matomo",
    "mautic",
    "mermaid",
    "metabase",
    "minio",
    "minio-console",
    "mydraft",
    "n8n",
    "npm",
    "nb",
    "nextcloud",
    "oneuptime",
    "penpot",
    "plane",
    "plantuml",
    "posthog",
    "postiz",
    "seonaut",
    "serpbear",
    "taiga",
    "weaviate",
    "webstudio",
    "webui",
  ])
}
