use crate::config::Config;

#[derive(Copy, Clone)]
pub enum ShellKind {
    Zsh,
    Bash,
}

pub fn render(config: &Config, kind: ShellKind) -> String {
    let mut out = String::from("# generated by auto-sudo shell\n");
    for (command, command_config) in &config.commands {
        if !command_config.should_wrap() {
            continue;
        }
        if !valid_function_name(command) {
            out.push_str(&format!(
                "# skipped invalid shell function name: {command}\n"
            ));
            continue;
        }
        out.push_str(&render_function(command, kind));
        out.push('\n');
    }
    out
}

fn render_function(command: &str, kind: ShellKind) -> String {
    let array_decl = match kind {
        ShellKind::Zsh => "  local _auto_sudo_pipe_args=()\n",
        ShellKind::Bash => "  local _auto_sudo_pipe_args=()\n",
    };

    format!(
        r#"{command}() {{
  local _auto_sudo_prefix
{array_decl}  [[ ! -t 0 ]] && _auto_sudo_pipe_args+=(--stdin-piped)
  [[ ! -t 1 ]] && _auto_sudo_pipe_args+=(--stdout-piped)
  _auto_sudo_prefix="$(auto-sudo decide "${{_auto_sudo_pipe_args[@]}}" -- {quoted} "$@")" || return $?
  if [[ -n "$_auto_sudo_prefix" ]]; then
    printf '\033[1;33mAuto Sudo {command}\033[0m' >&2
    (( $# > 0 )) && printf ' %s' "$*" >&2
    printf '\n' >&2
    eval "command ${{_auto_sudo_prefix}}{quoted} \"\$@\""
  else
    command {quoted} "$@"
  fi
}}
"#,
        command = command,
        array_decl = array_decl,
        quoted = shell_word(command)
    )
}

fn valid_function_name(value: &str) -> bool {
    let mut chars = value.chars();
    let Some(first) = chars.next() else {
        return false;
    };
    (first.is_ascii_alphabetic() || first == '_')
        && chars.all(|ch| ch.is_ascii_alphanumeric() || matches!(ch, '_' | '-' | '.'))
}

fn shell_word(value: &str) -> String {
    if value
        .chars()
        .all(|ch| ch.is_ascii_alphanumeric() || matches!(ch, '_' | '-' | '.' | '/' | ':'))
    {
        value.to_string()
    } else {
        format!("'{}'", value.replace('\'', "'\\''"))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn renders_wrapped_command() {
        let config: Config = serde_yaml::from_str(
            r#"
version: 1
commands:
  vim:
    wrap: true
    rules:
      - name: always
        when:
          always: true
"#,
        )
        .unwrap();
        let body = render(&config, ShellKind::Zsh);
        assert!(body.contains("vim()"));
        assert!(body.contains("auto-sudo decide"));
        assert!(body.contains("--stdin-piped"));
        assert!(body.contains("printf '\\033[1;33mAuto Sudo vim\\033[0m'"));
    }
}
