import type { GraphDocument, PatchOperation } from "./types";

export const demoDocument: GraphDocument = {
  id: "trd-demo",
  slug: "holograph-walking-skeleton",
  title: "The Robot Drafts vnext walking skeleton",
  version: 1,
  updatedAt: "2026-07-22T06:55:00Z",
  summary:
    "Fixture-backed code graph proving the M1 load, view, focus, drill, and detail-panel path.",
  nodes: [
    {
      id: "root",
      label: "HoloGraph",
      kind: "system",
      description: "Web-native graph document workspace for The Robot Drafts.",
      metrics: { complexity: 72, churn: 38, risk: 44 },
      status: "draft",
    },
    {
      id: "docs",
      label: "Docs",
      kind: "package",
      parentId: "root",
      packageName: "backend/lib/holograph/docs",
      description: "GraphDocument persistence, versions, and fixture import.",
      metrics: { complexity: 48, churn: 24, risk: 22 },
      members: ["create_document/2", "get_document!/1", "append_version/2"],
      status: "review",
    },
    {
      id: "graph",
      label: "Graph",
      kind: "package",
      parentId: "root",
      packageName: "frontend/src/graph",
      description: "Layout payload, traversal, metrics, and scene graph contracts.",
      metrics: { complexity: 66, churn: 42, risk: 39 },
      members: ["packGraph()", "buildLodTree()", "tracePath()"],
      status: "hot",
    },
    {
      id: "renderer",
      label: "Renderer",
      kind: "service",
      parentId: "root",
      packageName: "frontend/src/renderer",
      description: "Interactive visual renderer behind the IRenderer seam.",
      metrics: { complexity: 61, churn: 34, risk: 32 },
      members: ["loadScene()", "focusNode()", "pickNode()", "highlightTrace()"],
      status: "draft",
    },
    {
      id: "collab",
      label: "Realtime Collab",
      kind: "service",
      parentId: "root",
      packageName: "backend/lib/holograph_web/channels",
      description: "Phoenix channel contract for patches, presence, and cursors.",
      metrics: { complexity: 54, churn: 31, risk: 28 },
      members: ["graph:doc:*", "patch:apply", "cursor:move"],
      status: "draft",
    },
    {
      id: "draft-agent",
      label: "Draft Agent",
      kind: "agent",
      parentId: "root",
      packageName: "backend/lib/holograph/agents",
      description: "Spec-to-patch assistant that proposes reviewable graph edits.",
      metrics: { complexity: 69, churn: 45, risk: 55 },
      members: ["draft_from_spec/2", "validate_patch/1", "explain_delta/1"],
      status: "review",
    },
    {
      id: "postgres",
      label: "Graph Store",
      kind: "database",
      parentId: "root",
      packageName: "app-timescaledb",
      description: "Postgres-backed document versions and collab event log.",
      metrics: { complexity: 35, churn: 12, risk: 24 },
      members: ["graph_documents", "graph_document_versions", "collab_events"],
      status: "stable",
    },
    {
      id: "api",
      label: "REST API",
      kind: "interface",
      parentId: "docs",
      packageName: "backend/lib/holograph_web/controllers",
      description: "Versioned /api/v1 document and patch endpoints.",
      metrics: { complexity: 42, churn: 19, risk: 21 },
      members: ["GET /api/v1/docs/:id", "POST /api/v1/docs", "POST /patches"],
      status: "draft",
    },
    {
      id: "patch-format",
      label: "Patch Format",
      kind: "class",
      parentId: "graph",
      packageName: "docs/specs/patch-format.md",
      description: "Ordered operation list; one applied batch equals one undo step.",
      metrics: { complexity: 58, churn: 18, risk: 30 },
      members: ["add_node", "connect", "rename", "reparent", "delete"],
      status: "review",
    },
    {
      id: "layout",
      label: "Sphere Pack v1",
      kind: "function",
      parentId: "graph",
      packageName: "frontend/src/lib/holograph/layout.ts",
      description: "Deterministic containment-aware layout for the M1 renderer payload.",
      metrics: { complexity: 51, churn: 27, risk: 26 },
      members: ["packDocument()", "childRing()", "metricRadius()"],
      status: "draft",
    },
    {
      id: "importer",
      label: "TRD Importer",
      kind: "function",
      parentId: "docs",
      packageName: "tools/trd-converter",
      description: "Server-side wrapper target for PlantUML and .trd-yaml roundtrip.",
      metrics: { complexity: 46, churn: 17, risk: 18 },
      members: ["puml -> trd-yaml", "trd-yaml -> puml"],
      status: "stable",
    },
    {
      id: "detail-panel",
      label: "Detail Panel",
      kind: "class",
      parentId: "renderer",
      packageName: "frontend/src/components/holograph",
      description: "Selection inspector for members, metrics, status, and patch actions.",
      metrics: { complexity: 32, churn: 21, risk: 14 },
      members: ["selectedNode", "metrics", "members", "draft actions"],
      status: "draft",
    },
  ],
  edges: [
    { id: "e1", sourceId: "root", targetId: "docs", kind: "contains", label: "domain" },
    { id: "e2", sourceId: "root", targetId: "graph", kind: "contains", label: "domain" },
    { id: "e3", sourceId: "root", targetId: "renderer", kind: "contains", label: "domain" },
    { id: "e4", sourceId: "root", targetId: "collab", kind: "contains", label: "domain" },
    { id: "e5", sourceId: "root", targetId: "draft-agent", kind: "contains", label: "domain" },
    { id: "e6", sourceId: "root", targetId: "postgres", kind: "stores", label: "versions" },
    { id: "e7", sourceId: "docs", targetId: "api", kind: "publishes", label: "/api/v1" },
    { id: "e8", sourceId: "graph", targetId: "patch-format", kind: "depends_on", label: "mutations" },
    { id: "e9", sourceId: "graph", targetId: "layout", kind: "calls", label: "layout" },
    { id: "e10", sourceId: "renderer", targetId: "layout", kind: "depends_on", label: "scene payload" },
    { id: "e11", sourceId: "renderer", targetId: "detail-panel", kind: "publishes", label: "selection" },
    { id: "e12", sourceId: "collab", targetId: "patch-format", kind: "patches", label: "apply/reject" },
    { id: "e13", sourceId: "draft-agent", targetId: "patch-format", kind: "patches", label: "proposal" },
    { id: "e14", sourceId: "api", targetId: "postgres", kind: "stores", label: "document versions" },
    { id: "e15", sourceId: "docs", targetId: "importer", kind: "calls", label: "fixture import" },
  ],
};

export const demoPatches: PatchOperation[] = [
  {
    id: "p-001",
    type: "add_node",
    targetId: "renderer",
    label: "Add minimap overlay to renderer shell",
    status: "applied",
  },
  {
    id: "p-002",
    type: "connect",
    targetId: "draft-agent",
    label: "Link draft agent proposals to patch review queue",
    status: "review",
  },
  {
    id: "p-003",
    type: "rename",
    targetId: "layout",
    label: "Rename sphere pack seam to ILayout",
    status: "queued",
  },
];

export function listDocuments() {
  return [
    {
      id: demoDocument.id,
      slug: demoDocument.slug,
      title: demoDocument.title,
      version: demoDocument.version,
      updatedAt: demoDocument.updatedAt,
      summary: demoDocument.summary,
      nodeCount: demoDocument.nodes.length,
      edgeCount: demoDocument.edges.length,
    },
  ];
}
