---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: lacrosse-pg-primary-secrets
  namespace: lacrosse-infra
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgA74dkyKqOAfEtwahzJf9rDdTJn7VXiqAMA7ZvRX8eNu2CEH2N09FnKZmSjttUtq61INK3wHnYfigoH/+VRM9d/iDreVTJDhODXv2Fc236jWGkijD6e/tIaNav4OWsNVJT2OPFrzUu622brlCWu6NiCd6N00Iq3nKeScDm9SPthzXb7yT4xjeTgB7xr6xPweQ/n9J3FyOlokcKNACpbPVzS4UrmzMVABWPoASccm9dXhqdrwO/unMUT4IMTyxIAtRBR5Dq3vcA3OWTOduoGCtKx5EL+qXCSU+6BK8SSgb9ADrbYujDywt2alDSH853gEU+munQVPrGXM1HqyiOjFH5mytzm4vWGc36DBIGOz6sCLuLvbcZuI5FEvjesmyqB5jLfZEv26z3AT9Lyw5r+FXxJOUxETqvogaZdKG8XEKDWVM/zZClDXcoYAQb1Ptj6hdJvAQkDKfPBmJwijJkvUdcmtBqh0V+gqXcsRoocc6Ll0WCiBOCCS0peybfXOGM4DmyPGOTfgcnRLKPzP8qd1P6hBlRwT4RknH1wyAUirAsawFttMMICEJP02wCRatRtQrqX0Pp827QAUr0D+TWA8zUBPFTRKwOlodsPzx6ZMetj0GBXKpxduK+98/B/c0TygHj4C74qTkebmqLYiz9HteCtr6/MOXfj7mpg/6RxRQVtdY+dkniWE4V6FAykDgAEVOU2zW0KcZ4JuqoSm/6bt3ztbVzXKVfbv6XwlRphRw2CHA==
  template:
    metadata:
      name: lacrosse-pg-primary-secrets
      namespace: lacrosse-infra
