---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: lacrosse-pg-warehouse-secrets
  namespace: lacrosse-infra
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBaODAJ3Eef0J8kPhkUaWIfcSTqbc56tWkRkoi8X6MqUefU8V8Eg8fd5ilFOssYOojiKEVEZ3CpLQwx/lkVhbMSBtXqUfxzQ1wTmAjY7J+tqHQebYhlNIx2ADYeM/2wkNdHWHgQx/D/ZehoYfpfz9iqKRiznToNdRG9LQq078HqKweC/xI4t5aqE84c29k+Zz0aoTXSPt6Uqeq0+AGzTdxSRxSYyaWpJm9yEVAfEyRNGFJ9svtO4evDtYoVrh1YDA+6L7yy9wO8GXuj2jmYEH9wUIltPgpoqNu2BKn3ZxTXL17f1UVolT9HxWkFuRuqHmfcWPr2+vrez0QH7IGJLD1tK3+4afrXQp6CQVHFBUEOEpXkFPfGE1xBsb3AzSlNbOBY5CT1nOY1nWVYAFTvZDQ2p6rCXSszUiJsQQpKbDjjX+AhRY/wtCEWd1SD9GG1A87WQxhacBiDkITeyNFhHa646Qtr8sZJHKr14hUM63VQO6E7EHBLUuwnidVePe+NDUesAXYa2G+kyb7vMGDJGBn2mgGxunY4ggw/b/DMjTbRPJMpuBBH43sX+YTexsqwjXYhDV869V9KoRWtMxqYthDudfhYZ/S/0juhCkmzDtlEHczz6znmE38zP7LEnaEEkMy6VAGgpc4hIb8x9eUsq8GoL9EjJGl6vT6KGe6Oj6Ho+pnAs5hf8/pz7TKe1CFXvdYkMyJeetaWUhg04s2b1ZXF4SVVRu+cxNYn5r4GIloi7A==
  template:
    metadata:
      name: lacrosse-pg-warehouse-secrets
      namespace: lacrosse-infra
