#!/usr/bin/env bash
# Generate the Lacrosse staging credentials ONCE, then seal them into committed
# SealedSecrets. The sealed files are the source of truth — Terraform only
# applies them (../secrets.tf), so the values can never be regenerated by an
# apply. Re-running reuses the gitignored plaintext store, so values stay stable.
#
# Plaintext store (gitignored): secrets/unsealed/values.env
#
# Requires: kubectl + kubeseal, with the sealed-secrets controller running
# (kube-system/sealed-secrets-controller). Cert fetch is read-only:
#   KUBECONFIG=~/.kube/noizu/config kubeseal --fetch-cert \
#     --controller-name sealed-secrets-controller \
#     --controller-namespace kube-system
#
#   ./seal-secrets.sh
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"

KUBECONFIG="${KUBECONFIG:-$HOME/.kube/noizu/config}"
KUBE_CONTEXT="${KUBE_CONTEXT:-noizu}"
CNS="${CONTROLLER_NS:-kube-system}"
CNAME="${CONTROLLER_NAME:-sealed-secrets-controller}"

INFRA_NS="${INFRA_NS:-lacrosse-infra}"

STORE="$HERE/unsealed"
VALUES="$STORE/values.env"

export KUBECONFIG

rand() { LC_ALL=C tr -dc 'A-Za-z0-9' < /dev/urandom | head -c "$1"; }

mkdir -p "$STORE"
chmod 700 "$STORE" 2>/dev/null || true
touch "$VALUES"; chmod 600 "$VALUES"

ensure() {  # KEY LEN — append KEY=<rand LEN> only if KEY is not already set.
  local key="$1" len="$2"
  if ! grep -q "^${key}=" "$VALUES"; then
    printf '%s=%s\n' "$key" "$(rand "$len")" >> "$VALUES"
    echo "   + ${key}"
  fi
}

echo ">> generating/reusing values in $VALUES"
ensure PG_PRIMARY_PASSWORD 32
ensure PG_WAREHOUSE_PASSWORD 32
ensure SIGNOZ_ADMIN_PASSWORD 24
ensure SIGNOZ_JWT_SECRET 64

# shellcheck disable=SC1090
source "$VALUES"

# kubeseal uses the controller's public cert; fetching it is read-only. If the
# cluster is unreachable, emit plaintext Secret manifests into unsealed/ instead
# and print instructions, so authoring can proceed offline.
seal() {  # <secret-name> <namespace> <kubectl --from-literal args...>
  local name="$1" ns="$2"; shift 2
  if kubectl create secret generic "$name" -n "$ns" "$@" --dry-run=client -o yaml \
       | kubeseal --controller-namespace "$CNS" --controller-name "$CNAME" --format yaml \
       > "$HERE/$name.sealedsecret.yaml" 2>/dev/null; then
    echo "   sealed $name -> $ns"
  else
    kubectl create secret generic "$name" -n "$ns" "$@" --dry-run=client -o yaml \
      > "$STORE/$name.plain.yaml"
    echo "   !! kubeseal failed; wrote PLAINTEXT $STORE/$name.plain.yaml (gitignored)"
    SEAL_FAILED=1
  fi
}

echo ">> sealing (controller $CNS/$CNAME)"
seal lacrosse-pg-primary-secrets   "$INFRA_NS" --from-literal=POSTGRES_PASSWORD="$PG_PRIMARY_PASSWORD"
seal lacrosse-pg-warehouse-secrets "$INFRA_NS" --from-literal=POSTGRES_PASSWORD="$PG_WAREHOUSE_PASSWORD"
seal lacrosse-signoz-secrets       "$INFRA_NS" \
  --from-literal=ADMIN_PASSWORD="$SIGNOZ_ADMIN_PASSWORD" \
  --from-literal=JWT_SECRET="$SIGNOZ_JWT_SECRET"

echo
if [[ "${SEAL_FAILED:-0}" == "1" ]]; then
  echo "One or more seals FAILED. Plaintext manifests are in $STORE (gitignored)."
  echo "Once the controller is reachable, re-run this script to produce sealed files."
  exit 1
fi
echo "Done. Commit the *.sealedsecret.yaml files in $HERE."
echo "Plaintext (gitignored): $VALUES"
echo "SigNoz admin password (first-login bootstrap): $SIGNOZ_ADMIN_PASSWORD"
